[package]
name = "lit-node-simple-api"
version = "2.0.1"
edition.workspace = true
description = "Simple API for the Lit Node.  Wraps the RUST SDK into a simple API."
license = "Apache-2.0"

[features]
default = []

[dependencies]
data-encoding.workspace = true
ed25519-dalek.workspace = true
ethabi.workspace = true
ethers.workspace = true
hd-keys-curves-wasm.workspace = true
hex.workspace = true
lit-rust-crypto.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror = "2.0"
rocket = { version = "0.5.1", features = ["json"] }
rocket_cors = { version = "0.6.0" }
tracing.workspace = true
rand = "0.8.5"
lit-node-testnet = { path = "../lit-node-testnet" }
lit-node-core = { path = "../lit-node-core" }
lit-core = { path = "../../lit-core/lit-core" }


[dev-dependencies]
rand_chacha = "0.3.1"
rand_core = "0.6.4"