use rocket::http::Status;
use serde::{Deserialize, Serialize};
use lit_node_core::SigningScheme;
/// EVM chain RPC and wallet info.
#[derive(Debug, Clone, Serialize, Deserialize)]

pub struct ChainInfo {
    pub chain_name: &'static str,
    pub chain_id: u64,
    pub is_evm: bool,
    pub token: &'static str,
    pub rpc_url: &'static str,
    pub signing_scheme: SigningScheme,
    pub derivation_path: &'static str,
}

/// Supported EVM chains with their RPC and derivation data.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Chain {
    Ethereum,
    BnbSmartChain,
    ArbitrumOne,
    Base,
    AvalancheCChain,
    PolygonPos,
    Optimism,
    Blast,
    Scroll,
    Mantle,
    Linea,
    Cronos,
    Mode,
    ZkSyncEra,
    PulseChain,
    Fantom,
    MantaPacific,
    Celo,
    Kava,
    Gnosis,
    Metis,
    Astar,
    Moonbeam,
    Core,
    Zora,
    Klaytn,
    Canto,
    Moonriver,
    Taiko,
    Flare,
    ConfluxESpace,
    Aurora,
    Telos,
    BobaNetwork,
    Heco,
    OkxChain,
    ZkFair,
    Wemix30,
    Kcc,
    IoTeX,
    Evmos,
    Meter,
    MilkomedaC1,
    Syscoin,
    Dogechain,
    Fuse,
    Shibarium,
    ThunderCore,
    ReiNetwork,
    XLayer,
    Yellowstone,
    // Non-EVM chains
    Tron,
    Solana,
    Sui,
    Bitcoin,
    Aptos,
    Near,
    Cardano,
    Stacks,
    CosmosHub,
    Stellar,
}

impl Chain {
    pub fn try_from_str(chain: &str) -> Result<Self, Status> {
        match chain {
            "ethereum" => Ok(Self::Ethereum),
            "bnb" => Ok(Self::BnbSmartChain),
            "arbitrum" => Ok(Self::ArbitrumOne),
            "base" => Ok(Self::Base),
            "avalanche" => Ok(Self::AvalancheCChain),
            "polygon" => Ok(Self::PolygonPos),
            "optimism" => Ok(Self::Optimism),
            "blast" => Ok(Self::Blast),
            "scroll" => Ok(Self::Scroll),
            "mantle" => Ok(Self::Mantle),
            "linea" => Ok(Self::Linea),
            "cronos" => Ok(Self::Cronos),
            "mode" => Ok(Self::Mode),
            "zksync" => Ok(Self::ZkSyncEra),
            "pulsechain" => Ok(Self::PulseChain),
            "fantom" => Ok(Self::Fantom),
            "manta" => Ok(Self::MantaPacific),
            "celo" => Ok(Self::Celo),
            "kava" => Ok(Self::Kava),
            "gnosis" => Ok(Self::Gnosis),
            "metis" => Ok(Self::Metis),
            "astar" => Ok(Self::Astar),
            "moonbeam" => Ok(Self::Moonbeam),
            "core" => Ok(Self::Core),
            "zora" => Ok(Self::Zora),
            "klaytn" => Ok(Self::Klaytn),
            "canto" => Ok(Self::Canto),
            "moonriver" => Ok(Self::Moonriver),
            "taiko" => Ok(Self::Taiko),
            "flare" => Ok(Self::Flare),
            "conflux" => Ok(Self::ConfluxESpace),
            "aurora" => Ok(Self::Aurora),
            "telos" => Ok(Self::Telos),
            "boba" => Ok(Self::BobaNetwork),
            "heco" => Ok(Self::Heco),
            "okx" => Ok(Self::OkxChain),
            "zkfair" => Ok(Self::ZkFair),
            "wemix" => Ok(Self::Wemix30),
            "kcc" => Ok(Self::Kcc),
            "iotex" => Ok(Self::IoTeX),
            "evmos" => Ok(Self::Evmos),
            "meter" => Ok(Self::Meter),
            "milkomeda" => Ok(Self::MilkomedaC1),
            "syscoin" => Ok(Self::Syscoin),
            "dogechain" => Ok(Self::Dogechain),
            "fuse" => Ok(Self::Fuse),
            "shibarium" => Ok(Self::Shibarium),
            "thundercore" => Ok(Self::ThunderCore),
            "rei" => Ok(Self::ReiNetwork),
            "xlayer" => Ok(Self::XLayer),
            "tron" => Ok(Self::Tron),
            "solana" => Ok(Self::Solana),
            "sui" => Ok(Self::Sui),
            "bitcoin" => Ok(Self::Bitcoin),
            "aptos" => Ok(Self::Aptos),
            "near" => Ok(Self::Near),
            "cardano" => Ok(Self::Cardano),
            "stacks" => Ok(Self::Stacks),
            "cosmos" => Ok(Self::CosmosHub),
            "stellar" => Ok(Self::Stellar),
            "yellowstone" => Ok(Self::Yellowstone),
            _ => Err(Status::NotFound),
        }
    }
    pub fn info(self) -> ChainInfo {
        match self {
            Self::Yellowstone => ChainInfo {
                chain_name: "Yellowstone",
                chain_id: 175188,
                is_evm: true,
                token: "LitKey",
                rpc_url: "https://yellowstone-rpc.litprotocol.com",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Ethereum => ChainInfo {
                chain_name: "Ethereum",
                chain_id: 1,
                is_evm: true,
                token: "ETH",
                rpc_url: "https://eth.llamarpc.com",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::BnbSmartChain => ChainInfo {
                chain_name: "BNB Smart Chain",
                chain_id: 56,
                is_evm: true,
                token: "BNB",
                rpc_url: "https://bsc-dataseed.binance.org",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::ArbitrumOne => ChainInfo {
                chain_name: "Arbitrum One",
                chain_id: 42161,
                is_evm: true,
                token: "ETH",
                rpc_url: "https://arb1.arbitrum.io",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Base => ChainInfo {
                chain_name: "Base",
                chain_id: 8453,
                is_evm: true,
                token: "ETH",
                rpc_url: "https://mainnet.base.org",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::AvalancheCChain => ChainInfo {
                chain_name: "Avalanche C-Chain",
                chain_id: 43114,
                is_evm: true,
                token: "AVAX",
                rpc_url: "https://api.avax.network",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::PolygonPos => ChainInfo {
                chain_name: "Polygon POS",
                chain_id: 137,
                is_evm: true,
                token: "POL",
                rpc_url: "https://polygon-rpc.com",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Optimism => ChainInfo {
                chain_name: "Optimism",
                chain_id: 10,
                is_evm: true,
                token: "ETH",
                rpc_url: "https://mainnet.optimism.io",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Blast => ChainInfo {
                chain_name: "Blast",
                chain_id: 81457,
                is_evm: true,
                token: "ETH",
                rpc_url: "https://rpc.blast.io",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Scroll => ChainInfo {
                chain_name: "Scroll",
                chain_id: 534352,
                is_evm: true,
                token: "ETH",
                rpc_url: "https://rpc.scroll.io",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Mantle => ChainInfo {
                chain_name: "Mantle",
                chain_id: 5000,
                is_evm: true,
                token: "MNT",
                rpc_url: "https://rpc.mantle.xyz",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Linea => ChainInfo {
                chain_name: "Linea",
                chain_id: 59144,
                is_evm: true,
                token: "ETH",
                rpc_url: "https://rpc.linea.build",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Cronos => ChainInfo {
                chain_name: "Cronos",
                chain_id: 25,
                is_evm: true,
                token: "CRO",
                rpc_url: "https://evm.cronos.org",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Mode => ChainInfo {
                chain_name: "Mode",
                chain_id: 34443,
                is_evm: true,
                token: "ETH",
                rpc_url: "https://mainnet.mode.network",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::ZkSyncEra => ChainInfo {
                chain_name: "zkSync Era",
                chain_id: 324,
                is_evm: true,
                token: "ETH",
                rpc_url: "https://mainnet.era.zksync.io",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::PulseChain => ChainInfo {
                chain_name: "PulseChain",
                chain_id: 369,
                is_evm: true,
                token: "PLS",
                rpc_url: "https://rpc.pulsechain.com",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Fantom => ChainInfo {
                chain_name: "Fantom",
                chain_id: 250,
                is_evm: true,
                token: "FTM",
                rpc_url: "https://rpc.ftm.tools",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::MantaPacific => ChainInfo {
                chain_name: "Manta Pacific",
                chain_id: 169,
                is_evm: true,
                token: "ETH",
                rpc_url: "https://pacific-rpc.manta.network",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Celo => ChainInfo {
                chain_name: "Celo",
                chain_id: 42220,
                is_evm: true,
                token: "CELO",
                rpc_url: "https://forno.celo.org",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/52734'/0'/0/0",
            },
            Self::Kava => ChainInfo {
                chain_name: "Kava",
                chain_id: 2222,
                is_evm: true,
                token: "KAVA",
                rpc_url: "https://evm.kava.io",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/459'/0'/0/0",
            },
            Self::Gnosis => ChainInfo {
                chain_name: "Gnosis",
                chain_id: 100,
                is_evm: true,
                token: "xDAI",
                rpc_url: "https://rpc.gnosischain.com",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/700'/0'/0/0",
            },
            Self::Metis => ChainInfo {
                chain_name: "Metis",
                chain_id: 1088,
                is_evm: true,
                token: "METIS",
                rpc_url: "https://andromeda.metis.io",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Astar => ChainInfo {
                chain_name: "Astar",
                chain_id: 592,
                is_evm: true,
                token: "ASTR",
                rpc_url: "https://evm.astar.network",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Moonbeam => ChainInfo {
                chain_name: "Moonbeam",
                chain_id: 1284,
                is_evm: true,
                token: "GLMR",
                rpc_url: "https://rpc.api.moonbeam.network",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/1284'/0'/0/0",
            },
            Self::Core => ChainInfo {
                chain_name: "Core",
                chain_id: 1116,
                is_evm: true,
                token: "CORE",
                rpc_url: "https://rpc.coredao.org",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Zora => ChainInfo {
                chain_name: "Zora",
                chain_id: 7777777,
                is_evm: true,
                token: "ETH",
                rpc_url: "https://rpc.zora.energy",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Klaytn => ChainInfo {
                chain_name: "Klaytn",
                chain_id: 8217,
                is_evm: true,
                token: "KLAY",
                rpc_url: "https://public-node-api.klaytnapi.com",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/8217'/0'/0/0",
            },
            Self::Canto => ChainInfo {
                chain_name: "Canto",
                chain_id: 7700,
                is_evm: true,
                token: "CANTO",
                rpc_url: "https://canto.slingshot.observer",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Moonriver => ChainInfo {
                chain_name: "Moonriver",
                chain_id: 1285,
                is_evm: true,
                token: "MOVR",
                rpc_url: "https://rpc.api.moonriver.moonbeam.network",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/1285'/0'/0/0",
            },
            Self::Taiko => ChainInfo {
                chain_name: "Taiko",
                chain_id: 167000,
                is_evm: true,
                token: "ETH",
                rpc_url: "https://rpc.mainnet.taiko.xyz",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Flare => ChainInfo {
                chain_name: "Flare",
                chain_id: 14,
                is_evm: true,
                token: "FLR",
                rpc_url: "https://flare-api.flare.network",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::ConfluxESpace => ChainInfo {
                chain_name: "Conflux eSpace",
                chain_id: 1030,
                is_evm: true,
                token: "CFX",
                rpc_url: "https://evm.confluxrpc.com",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/503'/0'/0/0",
            },
            Self::Aurora => ChainInfo {
                chain_name: "Aurora",
                chain_id: 1313161554,
                is_evm: true,
                token: "ETH",
                rpc_url: "https://mainnet.aurora.dev",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Telos => ChainInfo {
                chain_name: "Telos",
                chain_id: 40,
                is_evm: true,
                token: "TLOS",
                rpc_url: "https://mainnet.telos.net",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::BobaNetwork => ChainInfo {
                chain_name: "Boba Network",
                chain_id: 288,
                is_evm: true,
                token: "ETH",
                rpc_url: "https://mainnet.boba.network",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Heco => ChainInfo {
                chain_name: "Heco",
                chain_id: 128,
                is_evm: true,
                token: "HT",
                rpc_url: "https://http-mainnet.hecochain.com",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::OkxChain => ChainInfo {
                chain_name: "OKXChain",
                chain_id: 66,
                is_evm: true,
                token: "OKT",
                rpc_url: "https://exchainrpc.okex.org",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::ZkFair => ChainInfo {
                chain_name: "ZkFair",
                chain_id: 42766,
                is_evm: true,
                token: "ZKF",
                rpc_url: "https://rpc.zkfair.io",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Wemix30 => ChainInfo {
                chain_name: "WEMIX 3.0",
                chain_id: 1111,
                is_evm: true,
                token: "WEMIX",
                rpc_url: "https://api.wemix.com",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Kcc => ChainInfo {
                chain_name: "KCC",
                chain_id: 321,
                is_evm: true,
                token: "KCS",
                rpc_url: "https://rpc-mainnet.kcc.network",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::IoTeX => ChainInfo {
                chain_name: "IoTeX",
                chain_id: 4689,
                is_evm: true,
                token: "IOTX",
                rpc_url: "https://babel-api.mainnet.iotex.io",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/304'/0'/0/0",
            },
            Self::Evmos => ChainInfo {
                chain_name: "Evmos",
                chain_id: 9001,
                is_evm: true,
                token: "EVMOS",
                rpc_url: "https://eth.bd.evmos.org:8545",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Meter => ChainInfo {
                chain_name: "Meter",
                chain_id: 82,
                is_evm: true,
                token: "MTRG",
                rpc_url: "https://rpc.meter.io",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::MilkomedaC1 => ChainInfo {
                chain_name: "Milkomeda C1",
                chain_id: 2002,
                is_evm: true,
                token: "ADA",
                rpc_url: "https://rpc-mainnet-cardano-evm.milkomeda.com",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Syscoin => ChainInfo {
                chain_name: "Syscoin",
                chain_id: 57,
                is_evm: true,
                token: "SYS",
                rpc_url: "https://rpc.syscoin.org",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/57'/0'/0/0",
            },
            Self::Dogechain => ChainInfo {
                chain_name: "Dogechain",
                chain_id: 2000,
                is_evm: true,
                token: "DC",
                rpc_url: "https://rpc.dogechain.dog",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Fuse => ChainInfo {
                chain_name: "Fuse",
                chain_id: 122,
                is_evm: true,
                token: "FUSE",
                rpc_url: "https://rpc.fuse.io",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::Shibarium => ChainInfo {
                chain_name: "Shibarium",
                chain_id: 109,
                is_evm: true,
                token: "BONE",
                rpc_url: "https://www.shibariumscan.com",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::ThunderCore => ChainInfo {
                chain_name: "ThunderCore",
                chain_id: 108,
                is_evm: true,
                token: "TT",
                rpc_url: "https://mainnet-rpc.thundercore.com",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::ReiNetwork => ChainInfo {
                chain_name: "REI Network",
                chain_id: 47805,
                is_evm: true,
                token: "REI",
                rpc_url: "https://rpc.rei.network",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            Self::XLayer => ChainInfo {
                chain_name: "X Layer",
                chain_id: 196,
                is_evm: true,
                token: "OKB",
                rpc_url: "https://xlayerrpc.okx.com",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/60'/0'/0/0",
            },
            // Non-EVM chains (is_evm: false)
            Self::Tron => ChainInfo {
                chain_name: "Tron",
                chain_id: 0,
                is_evm: false,
                token: "TRX",
                rpc_url: "https://api.trongrid.io",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/195'/0'/0/0",
            },
            Self::Solana => ChainInfo {
                chain_name: "Solana",
                chain_id: 0,
                is_evm: false,
                token: "SOL",
                rpc_url: "https://api.mainnet-beta.solana.com",
                signing_scheme: SigningScheme::SchnorrEd25519Sha512,
                derivation_path: "m/44'/501'/0'/0'",
            },
            Self::Sui => ChainInfo {
                chain_name: "Sui",
                chain_id: 0,
                is_evm: false,
                token: "SUI",
                rpc_url: "https://fullnode.mainnet.sui.io:443",
                signing_scheme: SigningScheme::SchnorrEd25519Sha512,
                derivation_path: "m/44'/784'/0'/0'/0'",
            },
            Self::Bitcoin => ChainInfo {
                chain_name: "Bitcoin",
                chain_id: 0,
                is_evm: false,
                token: "BTC",
                rpc_url: "https://blockstream.info",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/84'/0'/0'/0/0",
            },
            Self::Aptos => ChainInfo {
                chain_name: "Aptos",
                chain_id: 0,
                is_evm: false,
                token: "APT",
                rpc_url: "https://fullnode.mainnet.aptoslabs.com",
                signing_scheme: SigningScheme::SchnorrEd25519Sha512,
                derivation_path: "m/44'/637'/0'/0'/0'",
            },
            Self::Near => ChainInfo {
                chain_name: "Near",
                chain_id: 0,
                is_evm: false,
                token: "NEAR",
                rpc_url: "https://rpc.mainnet.near.org",
                signing_scheme: SigningScheme::SchnorrEd25519Sha512,
                derivation_path: "m/44'/397'/0'",
            },
            Self::Cardano => ChainInfo {
                chain_name: "Cardano",
                chain_id: 0,
                is_evm: false,
                token: "ADA",
                rpc_url: "https://cardano-mainnet.blockfrost.io",
                signing_scheme: SigningScheme::SchnorrEd25519Sha512,
                derivation_path: "m/1852'/1815'/0'",
            },
            Self::Stacks => ChainInfo {
                chain_name: "Stacks",
                chain_id: 0,
                is_evm: false,
                token: "STX",
                rpc_url: "https://stacks-node-api.mainnet.stacks.co",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/5757'/0'/0/0",
            },
            Self::CosmosHub => ChainInfo {
                chain_name: "Cosmos Hub",
                chain_id: 0,
                is_evm: false,
                token: "ATOM",
                rpc_url: "https://rpc.cosmos.network",
                signing_scheme: SigningScheme::EcdsaK256Sha256,
                derivation_path: "m/44'/118'/0'/0/0",
            },
            Self::Stellar => ChainInfo {
                chain_name: "Stellar",
                chain_id: 0,
                is_evm: false,
                token: "XLM",
                rpc_url: "https://horizon.stellar.org",
                signing_scheme: SigningScheme::SchnorrEd25519Sha512,
                derivation_path: "m/44'/148'/0'",
            },
        }
    }

    /// All supported EVM chains in the same order as the original data.
    pub fn all_evm_chains() -> &'static [Chain] {
        const ALL: &[Chain] = &[
            Chain::Ethereum,
            Chain::BnbSmartChain,
            Chain::ArbitrumOne,
            Chain::Base,
            Chain::AvalancheCChain,
            Chain::PolygonPos,
            Chain::Optimism,
            Chain::Blast,
            Chain::Scroll,
            Chain::Mantle,
            Chain::Linea,
            Chain::Cronos,
            Chain::Mode,
            Chain::ZkSyncEra,
            Chain::PulseChain,
            Chain::Fantom,
            Chain::MantaPacific,
            Chain::Celo,
            Chain::Kava,
            Chain::Gnosis,
            Chain::Metis,
            Chain::Astar,
            Chain::Moonbeam,
            Chain::Core,
            Chain::Zora,
            Chain::Klaytn,
            Chain::Canto,
            Chain::Moonriver,
            Chain::Taiko,
            Chain::Flare,
            Chain::ConfluxESpace,
            Chain::Aurora,
            Chain::Telos,
            Chain::BobaNetwork,
            Chain::Heco,
            Chain::OkxChain,
            Chain::ZkFair,
            Chain::Wemix30,
            Chain::Kcc,
            Chain::IoTeX,
            Chain::Evmos,
            Chain::Meter,
            Chain::MilkomedaC1,
            Chain::Syscoin,
            Chain::Dogechain,
            Chain::Fuse,
            Chain::Shibarium,
            Chain::ThunderCore,
            Chain::ReiNetwork,
            Chain::XLayer,
        ];
        ALL
    }

    /// All supported non-EVM chains.
    pub fn all_non_evm_chains() -> &'static [Chain] {
        const ALL: &[Chain] = &[
            Chain::Tron,
            Chain::Solana,
            Chain::Sui,
            Chain::Bitcoin,
            Chain::Aptos,
            Chain::Near,
            Chain::Cardano,
            Chain::Stacks,
            Chain::CosmosHub,
            Chain::Stellar,
        ];
        ALL
    }
}
