# WARNING: If this configuration is copied or renamed to live_testnet.toml, then the tests will be run against the live network.
# The default example file is live_testnet_b.toml, which is not used directly by the test runner. 
# To run the tests against the live network, create a file named live_testnet.toml based on this one and change the values below to the correct values for the live network.


# This file contains the configuration that causes tests to be run against one of the live networks.
# You can find the appropriate configuration values in lit-ansible, which contains the configuration for the live networks.
[testnet]
name = "naga-test"
chain_id = "175188"
chain_name = "yellowstone"
rpc_url = "https://yellowstone-rpc.litprotocol.com"
contract_resolver_address = "0x0A88e4A0A371F783fCc2dd802f214EAF48D1C6a9" 
